{% set name = "pynwb" %}
{% set version = "4.0.0" %}
{% set sha256 = "8233d7ee565fcff1d4c59689c69d8b3dab1c41ed6b1e45967a57144f099ababf" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pynwb-validate = pynwb.validation_cli:validation_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - h5py >=3.6.0
    - hdmf >=6.1.0,<7
    - numpy >=1.24.0
    - pandas >=1.4.0
    - python-dateutil >=2.8.2
    - platformdirs >=4.2.2

test:
  requires:
    - pip
    - hdf5plugin
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
    - test.py
  imports:
    - pynwb
  commands:
    - pip check
    - python ./test.py -p -i -b -r

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - bendichter
    - oruebel
    - rly
