{% set name = "pynwb" %}
{% set version = "2.0.0" %}
{% set sha256 = "c22c96dd255e69cee1835057d741613d52c2ea1c45b6a1ef7f87ebaa8a5055ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - h5py >=2.9,<4
    - hdmf >=3.1.1,<4
    - numpy >=1.16,<1.22
    - pandas >=1.0.5,<2
    - python-dateutil >=2.7,<3

test:
  imports:
    - pynwb
  source_files:
    - test.py
    - tests
  commands:
    - python ./test.py

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    Neurophysiology (NWB:N) is a project to develop a unified data format for
    cellular-based neurophysiology data, focused on the dynamics of groups of
    neurons measured under a large range of experimental conditions.
    The NWB:N team consists of neuroscientists and software developers
    who recognize that adoption of a unified data format is an important
    step toward breaking down the barriers to data sharing in neuroscience.
  doc_url: http://pynwb.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - bendichter
    - dorukozturk
    - jcfr
    - oruebel
    - rly
