{% set name = "pynwb" %}
{% set version = "2.3.1" %}
{% set sha256 = "c6981cfdb9a6b62e7094f84eff98ee34e91354ed9d26802e47b4e90594d13159" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - h5py >=2.10,<4
    - hdmf >=3.4.2,<4
    - numpy >=1.16,<1.24
    - pandas >=1.1.5,<2
    - python-dateutil >=2.7.3,<3

test:
  imports:
    - pynwb
  source_files:
    - test.py
    - tests
  requires:
    - pip
  commands:
    # - python ./test.py
    - pip check

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - bendichter
    - oruebel
    - rly
    - mavaylon1
