{% set name = "pynwb" %}
{% set version = "2.2.0" %}
{% set sha256 = "7a1a08688237cd7ff41daa43b625903b3068f7327a928d379b1c43bbdf37555d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - h5py >=2.10,<4
    - hdmf >=3.4.2,<4
    - numpy >=1.16,<1.24
    - pandas >=1.1.5,<2
    - python-dateutil >=2.7.3,<3

test:
  imports:
    - pynwb
  source_files:
    - test.py
    - tests
  requires:
    - pip
  commands:
    # - python ./test.py
    - pip check

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - ajtritt
    - bendichter
    - dorukozturk
    - jcfr
    - oruebel
    - rly
