{% set name = "pynwb" %}
{% set version = "2.8.3" %}
{% set sha256 = "e0683a9525ae389e87341eed9bd7908d4d0a7c35def74ce5822a707cca230959" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - setuptools
    - h5py >=2.10
    - hdmf >=3.14.5
    - numpy >=1.18
    - pandas >=1.1.5
    - python-dateutil >=2.7.3

test:
  requires:
    - python {{ python_min }}
    - pip
    - hdf5plugin
    - pytest
  source_files:
    - tests
    - test.py
  imports:
    - pynwb
  commands:
    - pip check
    - python ./test.py -p -i -b -r

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - bendichter
    - oruebel
    - rly
    - mavaylon1
    - stephprince
