{% set name = "pynwb" %}
{% set version = "1.3.3" %}
{% set sha256 = "f5a87d094153cba307bd34d5dde90efb712fdd275979defadcc59a9618795cb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<33]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - h5py >=2.9
    - hdmf >=1.6.4,<2
    - numpy >=1.16
    - pandas >=0.23
    - python-dateutil >=2.7
    - ruamel.yaml >=0.15

test:
  imports:
    - pynwb
  source_files:
    - test.py
    - tests
  commands:
    - python ./test.py

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    Neurophysiology (NWB:N) is a project to develop a unified data format for
    cellular-based neurophysiology data, focused on the dynamics of groups of
    neurons measured under a large range of experimental conditions.
    The NWB:N team consists of neuroscientists and software developers
    who recognize that adoption of a unified data format is an important
    step toward breaking down the barriers to data sharing in neuroscience.
  doc_url: http://pynwb.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - bendichter
    - dorukozturk
    - jcfr
    - oruebel
    - rly
