{% set name = "pynwb" %}
{% set version = "2.3.2" %}
{% set sha256 = "ccb53c5b8fe1b722d3dffffd439a266d53cdb4b4271c7d3ca2608798e90cb7b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools
    - h5py >=2.10
    - hdmf >=3.4.4
    - numpy >=1.16
    - pandas >=1.1.5
    - python-dateutil >=2.7.3

test:
  imports:
    - pynwb
  source_files:
    - test.py
    - tests
  requires:
    - pip
  commands:
    # - python ./test.py
    - pip check

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - bendichter
    - oruebel
    - rly
    - mavaylon1
