{% set name = "pynwb" %}
{% set version = "3.1.0" %}
{% set sha256 = "f659dcf5a8b18d3b7382c1883bc63d4a2f243b1e8a45ba911f8478191cf99998" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pynwb-validate = pynwb.validation_cli:validation_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - setuptools
    - h5py >=3.2.0
    - hdmf >=4.1.0,<5
    - numpy >=1.24.0
    - pandas >=1.2.0
    - python-dateutil >=2.8.2
    - platformdirs >=4.1.0

test:
  requires:
    - pip
    - hdf5plugin
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
    - test.py
  imports:
    - pynwb
  commands:
    - pip check
    - python ./test.py -p -i -b -r

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: A Python API for working with Neurodata stored in the NWB Format
  description: |
    PyNWB is a Python package for working with NWB files. It provides a
    high-level API for efficiently working with neurodata stored in the
    NWB format. 
  doc_url: http://pynwb.readthedocs.io/

extra:
  recipe-maintainers:
    - bendichter
    - oruebel
    - rly
    - mavaylon1
    - stephprince
