{% set name = "pynwb" %}
{% set version = "1.0.2" %}
{% set sha256 = "fed1f7ed0dac3de63e29f6a1335332c4bed8ab00a31d3a9bbd8965e44a652101" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - pandas
    - h5py
    - numpy
    - scipy
    - ruamel.yaml
    - python-dateutil
    - six
    - requests
    - hdmf

test:
  imports:
    - pynwb

about:
  home: https://github.com/NeurodataWithoutBorders/pynwb
  license: BSD-3-Clause
  license_file: license.txt
  summary: 'A Python API for working with Neurodata stored in the NWB Format'
  description: |
    Neurophysiology (NWB:N) is a project to develop a unified data format for
    cellular-based neurophysiology data, focused on the dynamics of groups of
    neurons measured under a large range of experimental conditions.
    The NWB:N team consists of neuroscientists and software developers
    who recognize that adoption of a unified data format is an important
    step toward breaking down the barriers to data sharing in neuroscience.
  doc_url: http://pynwb.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ajtritt
    - bendichter
    - dorukozturk
    - jcfr
    - oruebel
